language: node_js
node_js:
- '0.12'
- '0.10'
after_success: tar czvf hubot-kodi-$TRAVIS_BRANCH.tar.gz package.json node_modules/
  index.coffee scripts/ README.md LICENSE
deploy:
- provider: npm
  email: mark@segfawlt.net
  api_key:
    secure: jIs674pjPlAMrMx/9dZwlMYVe4AnnRcAnP8w8E9EaIrNxREX0exI/CMScQio7S+UpP+TWVGliXTIEpw+LkuIxXRAZh9AxblRnezkn2e9Gg/J78T8P2RI9Vs6KMCKqkKH0g2skGOFy/ZAGkBz69PYB80WKL8gsr9JzvcE7/oJ8za5YUbCpn6Kd0F3x1agJbrfZeMylXT0e6+yc9VKHR9NMA7PAFiTFs0ZJT2fcrOjYwVYZZaoe3WDm4VzLgwc0K1QdCvRwCHNxDDUaqKnj3qKsxM16IW+9EJZCPfdOyjm1iQQrpSPHeqs7OLhhKn3y36nZIt8lrm4WgYt6rvv0ZS8lJIYB+FoAbLvHyTeWbijftwDSbfsMnsY3OcZNaunx2IOSqWoekO/yiIK4xDrn6spzBg+h7maLuB+d1hkWITAFQVZrL8YNc7NQp07nh6qEmlY5Ygm+rA7P9MJ90yHKMYJ0fMmQ5KFfe58lFhSJ9ZMUr1Q3bsEQhqvUbN3f6Xz5Hb69zBT9SN/0070hO2QGNdLjujqWOsmdXDO8dg/rfU7hFMOgxxqqbE1rG+s5/hEdwqesRziI4gkri1i3s60IUfnXsPv2fq27g6UUkVEEOVIraxlK/ncHc11PYpWH4EAMci/e02ZMyTOE+XnkQG+ozre9ZNXVX6JcFXcLyuJsI4yvbw=
  on:
    tags: true
    repo: markhuge/hubot-kodi
    all_branches: true
- provider: releases
  api_key:
    secure: etyqMw3zmAGHNh7AXbNHBEoOwMYetXS8ZZN4y7ZR09H8pTBBqQYbQCjSKahjgp4IOExlTCXmtfpxeX19jMiWVoJwdA6TGfKM5SRIGonsjVb7B7KayeFt/ak422D/S3/i833NYV66VIZofFUwT/12SfaArlM7auGlJ6R7p5TMf5sqceFDiEI7jqDi4WMLbp7L/VtzLw/LI+r6iEpUEpR2y/cgMwmAwGZwQMQfGAeooWgQHO55upm8b0I6gcWdogKekO/YNRpiggncnJt3ZHxPF9ZBmzlv78LpYPScKvZ1fxSlJ3DUTbXPTRFe8F+DmJVAqKyUAZwL4q8G9J+0J1whUgnJTHEiFK9jcme4RpppIlUPMbbQivlMqDq0LZTzK/mvdmVJ13aE2A7Amdzrtb+VRRM+hEHhd0khz47+CdIdBourmxg+mLYAs7XztPyM0OkPbFputr/m5Svmym1QUpCm1zMZ/r5MpYJsNybY7O1nwW7fFMYIiX35h5AVqpshrrmoAQueqiz1aUb/PqpmzJ9XkrutCNBhl4uWxzvVo1uK9HhYL3FbfPKimo7HoZIswP9lNO7YNw/6EJD5iZ3nTdRpeIhlIO5/E/PpvEAMu/lwg5/cQ+NQIaKA9yQpGLAuAbFYYab5U87N/XC+PgYuyxFkSzt3oPme75ZkpFGlZtT4Hso=
  file: hubot-kodi-$TRAVIS_BRANCH.tar.gz
  skip_cleanup: true
  on:
    repo: markhuge/hubot-kodi
    tags: true
    all_branches: true
